image: rocker/tidyverse:latest

pages:
  stage: deploy

  before_script:
    - apt update -qq
    - apt install --yes libssl-dev libssh2-1-dev libxml2-dev libcurl4-gnutls-dev libgit2-dev libmagick++-dev pandoc pandoc-citeproc libudunits2-dev libgdal-dev libglpk-dev

  script:
    - Rscript -e 'install.packages("pkgdown")'
    - Rscript -e 'devtools::install_deps(dependencies = TRUE)'
    - Rscript -e 'remotes::install_github("vidonne/unhcrtemplate")'
    - Rscript -e 'install.packages("crul", repos = "http://packages.ropensci.org")'
    - Rscript -e 'remotes::install_gitlab("dickoa/robotoolbox")'
    - Rscript -e 'pkgdown::build_site(override = list(destination = "public"))'

  artifacts:
    paths:
      - public
